### PR TITLE
Setup frontend project

### LINKED ISSUE #4: Setup the front project
- Create the project in `/client`.
- Install `create-react-app`(with typescript).
- Jest
- Sass

Architecture [is here](https://github.com/bellangerq/poule-poule/wiki/Architecture).

### PR DESCRIPTION
**Pull request by hissalht**
closes #4 

- Initialize project with `create-react-app`
- Add an example component `Button`
- Add example test file
- Add `yarn lint` command using `eslint`
- Add `yarn format` command using `prettier-eslint`
- Add pre-commit hooks to format and lint code
- Add `@reach/router` and add some placeholder routes
- add a README

Todo :
- (add Redux ?)
- ~~(use CSS modules ?, `styled-components` ?)~~

### CODE REVIEW

**Comment by hissalht** [comment]
How would you like to apply style to components @bellangerq ?
- Global styles but using some BEM naming convention
- Scoped classes, using [CSS modules](https://css-tricks.com/css-modules-part-1-need/)
- [styled-components](https://www.styled-components.com/docs/basics#motivation)

**Comment by ThunderDev1** [comment]
could you rename the root folder "client" as discussed

**Comment by hissalht** [comment]
> 
> 
> could you rename the root folder "client" as discussed

done !

**Comment by bellangerq** [comment]
Yeah I'm more for global styles with BEM naming convention.

**Pull request merged**
